#!/bin/bash

###echo "clean up exisiting docker desktop installation"
###sudo apt remove docker-desktop
###rm -r $HOME/.docker/desktop
###sudo rm /usr/local/bin/com.docker.cli
###sudo apt purge -y docker-desktop

echo "clean up exisiting docker installation"
sudo apt-get remove docker docker-engine docker.io containerd runc

echo "setup repository"
sudo apt-get update
sudo apt-get -y install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  
###echo "install docker desktop"
###wget -O docker-desktop.deb "https://desktop.docker.com/linux/main/amd64/docker-desktop-4.14.1-amd64.deb?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-linux-amd64"
###sudo apt-get update
###sudo apt-get -y install ./docker-desktop.deb


echo "Docker Engine, containerd, and Docker Compose"
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin


echo "launch docker desktop"
###systemctl --user start docker-desktop
sudo systemctl start docker
docker compose version
docker version

###enable docker desktop to start on login
###systemctl --user enable docker-desktop
###systemctl --user stop docker-desktop
